"""Recipient file management and .sops.yaml generation."""

from __future__ import annotations

from pathlib import Path

from loguru import logger

from augint_tools.team_secrets.models import UserRecord


def read_recipients_file(path: Path) -> list[UserRecord]:
    """Parse a recipients text file into UserRecord objects.

    Format: lines of age public keys, optionally preceded by # name comments.
    Blank lines and comment-only lines (without a following key) are skipped.

    Example:
        # alice
        age1abc...
        # bob
        age1def...
    """
    if not path.exists():
        return []

    records: list[UserRecord] = []
    pending_name = ""

    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped:
            pending_name = ""
            continue
        if stripped.startswith("# "):
            pending_name = stripped[2:].strip()
            continue
        if stripped.startswith("#"):
            # Comment without space (not a name marker)
            continue
        # This is a key line
        records.append(UserRecord(name=pending_name, public_key=stripped))
        pending_name = ""

    return records


def write_recipients_file(path: Path, records: list[UserRecord]) -> None:
    """Write a recipients text file from UserRecord objects."""
    lines: list[str] = []
    for record in records:
        if record.name:
            lines.append(f"# {record.name}")
        lines.append(record.public_key)
        lines.append("")  # Blank line separator

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def add_recipient(recipients_path: Path, user: UserRecord) -> None:
    """Add a recipient to a recipients file."""
    existing = read_recipients_file(recipients_path)

    # Check for duplicate public key
    for record in existing:
        if record.public_key == user.public_key:
            logger.info(f"User '{user.name}' already in {recipients_path.name}")
            return

    existing.append(user)
    write_recipients_file(recipients_path, existing)


def remove_recipient(recipients_path: Path, name: str) -> bool:
    """Remove a recipient by name from a recipients file.

    Returns True if the user was found and removed.
    """
    existing = read_recipients_file(recipients_path)
    filtered = [r for r in existing if r.name != name]

    if len(filtered) == len(existing):
        return False

    write_recipients_file(recipients_path, filtered)
    return True


def collect_all_recipients(recipients_dir: Path) -> list[str]:
    """Collect all unique public keys from all .txt files in the recipients directory."""
    keys: set[str] = set()
    if not recipients_dir.exists():
        return []

    for txt_file in sorted(recipients_dir.glob("*.txt")):
        records = read_recipients_file(txt_file)
        for record in records:
            keys.add(record.public_key)

    return sorted(keys)


def collect_team_recipients(recipients_dir: Path, team: str) -> list[str]:
    """Collect public keys from the team-wide recipients file."""
    team_file = recipients_dir / f"team-{team}.txt"
    records = read_recipients_file(team_file)
    return [r.public_key for r in records]


def collect_project_recipients(recipients_dir: Path, team: str, project: str) -> list[str]:
    """Collect public keys for a specific project (team + project-specific)."""
    keys: set[str] = set()

    # Team-wide recipients
    team_file = recipients_dir / f"team-{team}.txt"
    for record in read_recipients_file(team_file):
        keys.add(record.public_key)

    # Project-specific recipients
    project_file = recipients_dir / f"project-{project}.txt"
    if project_file.exists():
        for record in read_recipients_file(project_file):
            keys.add(record.public_key)

    return sorted(keys)


def generate_sops_yaml(repo_path: Path, team: str) -> str:
    """Generate .sops.yaml content from recipient files.

    Produces creation rules based on the recipients directory structure.
    Team-wide recipients apply to all projects. Project-specific files
    add additional recipients for specific path patterns.
    """
    recipients_dir = repo_path / "recipients"
    team_keys = collect_team_recipients(recipients_dir, team)

    # Check for project-specific recipient files
    project_files = sorted(recipients_dir.glob("project-*.txt"))

    lines: list[str] = [
        f"# Auto-generated by: ai-tools team-secrets {team} admin",
        "# Do not edit manually -- regenerated on add-user/remove-user/rotate.",
        f"# To add a user: ai-tools team-secrets {team} admin add-user <name> --pubkey <key>",
        "",
        "creation_rules:",
    ]

    # Project-specific rules first (higher priority)
    for pf in project_files:
        project_name = pf.stem.replace("project-", "", 1)
        project_keys = collect_project_recipients(recipients_dir, team, project_name)
        if project_keys and set(project_keys) != set(team_keys):
            age_str = ",".join(project_keys)
            lines.append(f"  # Project: {project_name}")
            lines.append(f"  - path_regex: projects/{project_name}/.*\\.enc\\.env$")
            lines.append("    age: >-")
            lines.append(f"      {age_str}")
            lines.append("")

    # Default rule for all projects (team-wide)
    if team_keys:
        age_str = ",".join(team_keys)
        lines.append("  # Default: all encrypted env files use team-wide recipients")
        lines.append("  - path_regex: projects/.*\\.enc\\.env$")
        lines.append("    age: >-")
        lines.append(f"      {age_str}")
    else:
        lines.append("  # No recipients configured yet.")
        lines.append(
            "  # Run: ai-tools team-secrets " + team + " admin add-user <name> --pubkey <key>"
        )
        lines.append("  - path_regex: projects/.*\\.enc\\.env$")
        lines.append('    age: ""')

    lines.append("")
    return "\n".join(lines)


def write_sops_yaml(repo_path: Path, team: str) -> None:
    """Regenerate and write .sops.yaml in the team repo."""
    content = generate_sops_yaml(repo_path, team)
    sops_path = repo_path / ".sops.yaml"
    sops_path.write_text(content)
    logger.debug(f"Regenerated {sops_path}")
